-- 코드를 작성해주세요
select ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO 
where ITEM_ID NOT IN
(select DISTINCT A.ITEM_ID FROM ITEM_TREE A INNER JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID) ORDER BY ITEM_ID DESC;

