-- 코드를 입력하세요
SELECT 
 cr.CAR_ID AS CAR_ID, cr.CAR_TYPE AS CAR_TYPE, FLOOR(DAILY_FEE * 30 * (100 - cp.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR cr
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN cp
ON cr.CAR_TYPE = cp.CAR_TYPE
WHERE (cr.CAR_TYPE = '세단' OR cr.CAR_TYPE = 'SUV') 
AND DAILY_FEE * 30 * (1 - DISCOUNT_RATE/100) >= 500000 AND
    DAILY_FEE * 30 * (1 - DISCOUNT_RATE/100) < 2000000 
AND cr.CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE LIKE '2022-11-%' OR END_DATE LIKE '2022-11-%')
        OR
        (START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-30'))

AND cp.DURATION_TYPE = '30일 이상'
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;