-- 코드를 입력하세요
SELECT H.FLAVOR
FROM FIRST_HALF H
INNER JOIN (
    SELECT SHIPMENT_ID,FLAVOR,SUM(TOTAL_ORDER) as TOTAL_ORDER  FROM JULY GROUP BY FLAVOR 
) AS J
ON H.SHIPMENT_ID = J.SHIPMENT_ID
ORDER BY H.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3
;
