-- 코드를 입력하세요
# SELECT M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE AS ID 
# FROM REST_REVIEW R JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID 
# GROUP BY R.MEMBER_ID ORDER BY COUNT(*) 
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, date_format(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE 
FROM REST_REVIEW R JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID 
where R.MEMBER_ID = (
select MEMBER_ID from REST_REVIEW group by MEMBER_ID Order by count(*) DESC limit 1)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT
;